spring:
  profiles:
    active: dev
  application:
    name: ctrl-zero
server:
  port: 9090
mybatis-flex:
  mapper-locations:
    - classpath*:/mapper/*.xml

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ctrl_zero
    username: root
    password: 12345678

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://47.103.13.111:3306/ctrl_zero
    username: root
    password: 12345678
